WIDTH  = 800
HEIGHT = 600

PLAYER_SHOOT_COOLDOWN = 5
PLAYER_MOVE_SPEED     = 5
PLAYER_MAX_HITPOINTS  = 5

ENEMY_SHOOT_COOLDOWN  = 35
ENEMY_MOVE_SPEED      = 2
ENEMY_MAX_HITPOINS    = 3

EXPLOSION_ANI_DELAY   = 5
WAVE_COOLDOWN         = 250
